# Generated by Django 2.0.5 on 2018-11-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
